apiVersion: v1
kind: Secret
metadata:
  name: backend-keycloak-bootstrap-secret
type: Opaque
stringData:
  CLIENT_SECRET: "123-456"
  keycloak_admin_username: keycloakadmin
  keycloak_admin_password: mykeycloakpassword
  ATTRIBUTES_USERNAME: user1
  ATTRIBUTES_PASSWORD: testuser123